# Generated by Django 3.1 on 2020-08-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer_a', models.CharField(max_length=100)),
                ('answer_b', models.CharField(max_length=100)),
                ('answer_c', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
    ]
